inherit_gem:
  rubocop-rspec: config/default.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "pkg/**/*"

Style/Documentation:
  Enabled: true

Metrics/MethodLength:
  Max: 65

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Layout/LineLength:
  Max: 120
